# Mutation Simulator Configuration
# All values are optional - defaults will be used if not specified

# =============================================================================
# WORLD SETTINGS
# =============================================================================

world:
  # Grid dimensions
  size: 20                      # Number of agent slots (used for square grid if width/height not specified)
  width: null                   # World width (optional, use with height for rectangular grid)
  height: null                  # World height (optional, use with width for rectangular grid)
  initial_coverage: 0.1         # Percentage of world to populate initially (0.1 = 10%)

# =============================================================================
# ENERGY SYSTEM
# =============================================================================

energy:
  # Basic energy settings
  decay: 1                      # Energy lost per tick
  
  # Initial energy for new agents
  initial_min: 20                # Minimum starting energy for new agents
  initial_max: 60               # Maximum starting energy for new agents

# =============================================================================
# ACTION COSTS
# =============================================================================

action_costs:
  base_cost: 0.2                # Base energy cost for any action
  
  attack:
    cost: 1.0                   # Additional energy cost for attacking
    damage: 3                   # Damage dealt when attacking
    energy_gain: 1              # Energy gained when attacking
  
  rest:
    energy_gain: 1              # Energy gained when resting
  
  replicate:
    cost: 10                     # Total energy cost to replicate
  
  move:
    dead_agent_energy_gain: 10  # Energy gained from eating dead agents

# =============================================================================
# AGENT MANAGEMENT
# =============================================================================

agent_management:
  # Population limits
  max_agent_count: 100          # Maximum number of concurrent agents
  parallel_processing_threshold: 5  # Minimum agents before using parallel processing
  max_parallel_threads: 8       # Maximum threads for parallel processing
  
  # Agent lifecycle
  max_lifespan: 1000            # Maximum cycles an agent can live (prevents immortal agents)
  
  # Process management
  response_timeout: 0.5         # Timeout for agent responses (seconds)
  process_cleanup_delay: 0.1    # Delay during process cleanup (seconds)
  graceful_death_timeout: 0.5   # Time to wait for graceful agent termination (seconds)
  default_timeout_ms: 1000      # Default timeout for agent responses (milliseconds)
  timeout_ms: 1000              # Agent response timeout in milliseconds

# =============================================================================
# SIMULATION CONTROL
# =============================================================================

simulation:
  # Timing and flow control
  delay: 0.05                   # Delay between ticks (seconds)
  max_ticks: null               # Maximum ticks to run (null = unlimited)
  auto_reset: true              # Auto-reset after extinction
  
  # Status logging
  status_log_frequency: 10      # Log status every N ticks
  status_log_early_threshold: 5 # Always log status for first N ticks
  
  # Auto-sizing fallbacks
  fallback_width: 80            # Fallback width if auto-sizing fails
  fallback_height: 24           # Fallback height if auto-sizing fails

# =============================================================================
# PARALLEL PROCESSING
# =============================================================================

parallel:
  enabled: false                # Enable parallel agent processing
  processor_count: null         # Number of processors to use (null = all available)

# =============================================================================
# MUTATION ENGINE
# =============================================================================

mutation:
  # Basic mutation parameters
  rate: 0.5                     # Probability of mutating each line
  probability: 0.05             # Probability of logging mutations
  
  # Numeric variations
  small_variation_min: 1        # Minimum variation for small numbers
  small_variation_max: 2        # Maximum variation for small numbers
  large_variation_percent: 0.2  # Variation percentage for large numbers
  
  # Probability variations
  probability_variation_min: 0.1    # Minimum probability variation
  probability_variation_max: 0.3    # Maximum probability variation
  probability_min_bound: 0.1        # Minimum probability bound
  probability_max_bound: 0.9        # Maximum probability bound
  
  # Threshold variations
  threshold_variation_min: 1        # Minimum threshold variation
  threshold_variation_max: 3        # Maximum threshold variation
  
  # Operator mutations
  operator_probability: 0.1         # Probability of operator mutation
  
  # Personality mutations
  personality_shift_min: -0.2       # Minimum personality shift
  personality_shift_max: 0.2        # Maximum personality shift
  personality_min_bound: 0.1        # Minimum personality bound
  personality_max_bound: 1.0        # Maximum personality bound
  personality_int_shift_min: -1     # Minimum integer personality shift
  personality_int_shift_max: 1      # Maximum integer personality shift
  personality_int_max_bound: 5      # Maximum integer personality bound

# =============================================================================
# GENETIC POOL
# =============================================================================

genetic_pool:
  # Pool management
  fingerprint_length: 16        # Length of genetic fingerprint
  survival_threshold: 100       # Survival threshold for lineage cleanup
  sample_size: 5                # Sample size for genetic statistics

# =============================================================================
# LOGGING SYSTEM
# =============================================================================

logging:
  # General logging
  level: debug                  # debug, info, warn, error, fatal
  
  # Agent logs
  max_agent_logs_per_simulation: 100  # Maximum agent logs per simulation before rotation
  
  # Survivor logs
  survivor_filename: survivors.log     # Survivor codes log file
  survivor_max_count: 3               # Maximum survivors to log

# =============================================================================
# VISUAL DISPLAY (CURSES MODE)
# =============================================================================

display:
  # General display settings
  visual_mode: true             # Use curses display by default
  
  # Layout settings
  bottom_panel_height: 8        # Height of the combined log and status area
  help_lines: 1                 # Number of lines for help information
  border_size: 3                # Space for Y-axis labels and top/left border
  fps: 30                       # Target display refresh rate (frames per second)
  status_panel_width_ratio: 0.33 # Width ratio of status panel (1/3 of status area)
  
  # Energy thresholds for display colors
  energy_very_high_threshold: 15  # Energy level for very high energy display
  energy_high_threshold: 10       # Energy level for high energy display  
  energy_medium_threshold: 5      # Energy level for medium energy display
  energy_low_threshold: 1         # Energy level for low energy display
  color_high_threshold: 8         # Color threshold for high energy (green)
  color_medium_threshold: 4       # Color threshold for medium energy (yellow)
  color_low_threshold: 1          # Color threshold for low energy (red)

# =============================================================================
# BENCHMARK SETTINGS
# =============================================================================

benchmark:
  default_size: 20              # Default world size for benchmarks
  default_generations: 10       # Default generations for benchmarks
  default_runs: 3               # Default number of benchmark runs

# =============================================================================
# AGENT BEHAVIOR DEFAULTS
# =============================================================================

agent_behavior:
  # Personality ranges
  personality_aggression_min: 0.3      # Minimum aggression value
  personality_aggression_max: 0.9      # Maximum aggression value
  personality_greed_min: 0.2           # Minimum greed value
  personality_greed_max: 0.8           # Maximum greed value
  personality_cooperation_min: 0.1     # Minimum cooperation value
  personality_cooperation_max: 0.6     # Maximum cooperation value
  
  # Death and survival
  personality_death_threshold_min: 1   # Minimum death threshold
  personality_death_threshold_max: 3   # Maximum death threshold
  death_history_check_length: 3        # Length of energy history to check for death
  
  # Replication behavior
  replication_energy_base: 6            # Base energy for replication calculation
  replication_energy_greed_multiplier: 4   # Greed multiplier for replication
  max_replications: 2                   # Maximum replications per agent
  min_replication_interval: 3           # Minimum turns between replications
  
  # Attack behavior
  attack_min_energy: 3                  # Minimum energy to attack
  weak_attack_min_energy: 2             # Minimum energy for weak attacks
  weak_attack_min_self_energy: 4        # Minimum self energy for weak attacks
  
  # Rest behavior
  rest_energy_base: 4                   # Base energy for rest calculation
  rest_energy_greed_multiplier: 3       # Greed multiplier for rest

# =============================================================================
# FILE SYSTEM PATHS
# =============================================================================

file_paths:
  agents_directory: agents              # Directory for agent files
  base_agent_path: examples/agents/ruby_agent.rb  # Path to base agent script
  agent_memory_base_path: /tmp/agents   # Base path for agent memory storage
  default_agent_executable: simple_move_agent.rb  # Default agent script

# =============================================================================
# FITNESS CALCULATION
# =============================================================================

fitness:
  energy_multiplier: 10         # Multiplier for energy in fitness calculation
  generation_multiplier: 5      # Multiplier for generation in fitness calculation